### ISSUE TITLE
Service account name for a task container

### ISSUE THREAD

**Issue by yurii-kryvosheia** [Scalr/agent-helm#58]
Currently the `default` serviceAccount is mounted into a _task_ pod. Is there a way to set different service account name?
The use case is vault authentication via aws backend.

**Comment by mermoldy** [comment]
Hi @yurii-kryvosheia, we're planning to change how service accounts are handled in the next agent's release. A task pod will use the service account inherited from the agent pod, which already can be configured via the Helm options (`serviceAccount.create`, `serviceAccount.name`). Will this behavior satisfy your needs?

**Comment by mermoldy** [comment]
Related discussion in the Slack Community channel: https://scalr-community.slack.com/archives/C0167NMGY9E/p1705053121598769

**Comment by yurii-kryvosheia** [comment]
> Hi @yurii-kryvosheia, we're planning to change how service accounts are handled in the next agent's release. A task pod will use the service account inherited from the agent pod, which already can be configured via the Helm options (`serviceAccount.create`, `serviceAccount.name`). Will this behavior satisfy your needs?

Yes, that'd be what we need. Just to confirm, when you say "next release," are you referring to the release scheduled for March?

**Comment by mermoldy** [comment]
@yurii-kryvosheia It's expected to be today.

**Comment by mermoldy** [comment]
@yurii-kryvosheia you can check out the latest chart https://github.com/Scalr/agent-helm/releases/tag/agent-k8s-0.5.7

**Comment by yurii-kryvosheia** [comment]
@mermoldy I confirm that task pods are now inheriting `serviceAccountName` from the agent pod. But why does it have `automountServiceAccountToken` set to `false`? It doesn't serve any purpose.

**Comment by mermoldy** [comment]
@yurii-kryvosheia We aim to avoid exposing any sensitive information to the run environment, unless there's a clear necessity.
