### ISSUE TITLE
Use StatefulSets instead of DaemonSet

### ISSUE THREAD

**Issue by pokgak** [Scalr/agent-helm#9]
Currently the the agent is deployed as [DaemonSet](https://github.com/Scalr/agent-helm/blob/c0d9a51051675aba1c714322b07e41b851fb65c5/charts/agent-k8s/templates/deployment.yaml#L2) which will deploy one copy of the scalr agent to ALL the nodes in the cluster (by  default). I don't see the need to have this deployed as DaemonSet and cannot find it documented anywhere too. I think this should be a StatefulSet or Deployment instead.

You can still have one agent listening to scalr that acts as the controller and it will start new pods for each runs. For monitoring the pods, the controller doesn't necessarily need to be on the same node as the runner pods. You can query k8s API to get the IP of the pod using labels to avoid having to know the exact pod name.

~As comparison, Atlantis Helm chart uses Statefulsets ([source](https://github.com/runatlantis/helm-charts/blob/main/charts/atlantis/templates/statefulset.yaml)) which makes more sense if you're thinking of persisting data across runs on the container.~ Comparing with Atlantis might not work here because scalr agents starts new pods for each run and not doing it running it directly inside the agent like Atlantis.

**Comment by mermoldy** [comment]
@pokgak Hi, the need for the agent to run on the same node as the run pod was discussed recently in [this issue](https://github.com/Scalr/agent-helm/issues/5). You can find the summary here: https://github.com/Scalr/agent-helm/issues/5#issuecomment-1624445809

You can also take a look at the docs for the upcoming controller/worker modes, set to be released in a week or two: https://github.com/Scalr/agent-helm/blob/feature/SCALRCORE-27380/charts/agent-k8s/README.md#additional-information

As for getting rid of DaemonSet, it will require a substantial reimplementation of the sidecar service for run pods. It's the next logical step in the Kubernetes agent's evolution and something we want to do in the future. But for now, it demands a lot of work and will take much more time and effort.

Please ask, if you have any further questions.

**Comment by pokgak** [comment]
Thanks @mermoldy appreciate the answers there. Linking here the answer from @maratkomarov for future reference: https://github.com/Scalr/agent-helm/issues/5#issuecomment-1624445809.
